/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DeliveryOrdersRouteImport } from './routes/delivery-orders'
import { Route as InternalTransfersRouteImport } from './routes/internal-transfers'
import { Route as InventoryAdjustmentsRouteImport } from './routes/inventory-adjustments'
import { Route as MoveHistoryRouteImport } from './routes/move-history'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReorderingRulesRouteImport } from './routes/reordering-rules'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsIdRouteImport } from './routes/receipts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryOrdersRoute = DeliveryOrdersRouteImport.update({
  id: '/delivery-orders',
  path: '/delivery-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalTransfersRoute = InternalTransfersRouteImport.update({
  id: '/internal-transfers',
  path: '/internal-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAdjustmentsRoute = InventoryAdjustmentsRouteImport.update({
  id: '/inventory-adjustments',
  path: '/inventory-adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveHistoryRoute = MoveHistoryRouteImport.update({
  id: '/move-history',
  path: '/move-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReorderingRulesRoute = ReorderingRulesRouteImport.update({
  id: '/reordering-rules',
  path: '/reordering-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceiptsRoute,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceiptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/delivery-orders': typeof DeliveryOrdersRoute
  '/internal-transfers': typeof InternalTransfersRoute
  '/inventory-adjustments': typeof InventoryAdjustmentsRoute
  '/move-history': typeof MoveHistoryRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reordering-rules': typeof ReorderingRulesRoute
  '/warehouses': typeof WarehousesRoute
  '/products/$id': typeof ProductsIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/products/': typeof ProductsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/delivery-orders': typeof DeliveryOrdersRoute
  '/internal-transfers': typeof InternalTransfersRoute
  '/inventory-adjustments': typeof InventoryAdjustmentsRoute
  '/move-history': typeof MoveHistoryRoute
  '/profile': typeof ProfileRoute
  '/reordering-rules': typeof ReorderingRulesRoute
  '/warehouses': typeof WarehousesRoute
  '/products/$id': typeof ProductsIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/products': typeof ProductsIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/delivery-orders': typeof DeliveryOrdersRoute
  '/internal-transfers': typeof InternalTransfersRoute
  '/inventory-adjustments': typeof InventoryAdjustmentsRoute
  '/move-history': typeof MoveHistoryRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reordering-rules': typeof ReorderingRulesRoute
  '/warehouses': typeof WarehousesRoute
  '/products/$id': typeof ProductsIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/products/': typeof ProductsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/delivery-orders'
    | '/internal-transfers'
    | '/inventory-adjustments'
    | '/move-history'
    | '/products'
    | '/profile'
    | '/receipts'
    | '/reordering-rules'
    | '/warehouses'
    | '/products/$id'
    | '/receipts/$id'
    | '/products/'
    | '/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/delivery-orders'
    | '/internal-transfers'
    | '/inventory-adjustments'
    | '/move-history'
    | '/profile'
    | '/reordering-rules'
    | '/warehouses'
    | '/products/$id'
    | '/receipts/$id'
    | '/products'
    | '/receipts'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/categories'
    | '/delivery-orders'
    | '/internal-transfers'
    | '/inventory-adjustments'
    | '/move-history'
    | '/products'
    | '/profile'
    | '/receipts'
    | '/reordering-rules'
    | '/warehouses'
    | '/products/$id'
    | '/receipts/$id'
    | '/products/'
    | '/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  AuthRoute: typeof AuthRoute
  DeliveryOrdersRoute: typeof DeliveryOrdersRoute
  InternalTransfersRoute: typeof InternalTransfersRoute
  InventoryAdjustmentsRoute: typeof InventoryAdjustmentsRoute
  MoveHistoryRoute: typeof MoveHistoryRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReceiptsRoute: typeof ReceiptsRouteWithChildren
  ReorderingRulesRoute: typeof ReorderingRulesRoute
  WarehousesRoute: typeof WarehousesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-orders': {
      id: '/delivery-orders'
      path: '/delivery-orders'
      fullPath: '/delivery-orders'
      preLoaderRoute: typeof DeliveryOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-transfers': {
      id: '/internal-transfers'
      path: '/internal-transfers'
      fullPath: '/internal-transfers'
      preLoaderRoute: typeof InternalTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-adjustments': {
      id: '/inventory-adjustments'
      path: '/inventory-adjustments'
      fullPath: '/inventory-adjustments'
      preLoaderRoute: typeof InventoryAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-history': {
      id: '/move-history'
      path: '/move-history'
      fullPath: '/move-history'
      preLoaderRoute: typeof MoveHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reordering-rules': {
      id: '/reordering-rules'
      path: '/reordering-rules'
      fullPath: '/reordering-rules'
      preLoaderRoute: typeof ReorderingRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof ReceiptsRoute
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof ReceiptsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ReceiptsRouteChildren {
  ReceiptsIdRoute: typeof ReceiptsIdRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
}

const ReceiptsRouteChildren: ReceiptsRouteChildren = {
  ReceiptsIdRoute: ReceiptsIdRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
}

const ReceiptsRouteWithChildren = ReceiptsRoute._addFileChildren(
  ReceiptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  AuthRoute: AuthRoute,
  DeliveryOrdersRoute: DeliveryOrdersRoute,
  InternalTransfersRoute: InternalTransfersRoute,
  InventoryAdjustmentsRoute: InventoryAdjustmentsRoute,
  MoveHistoryRoute: MoveHistoryRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReceiptsRoute: ReceiptsRouteWithChildren,
  ReorderingRulesRoute: ReorderingRulesRoute,
  WarehousesRoute: WarehousesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
